name: "SQL"
description: "SQL library for Nukkit. Provides mysql-connector and javax.persistence."
main: com.winthier.sql.SQLPlugin
version: "0.1"
author: "StarTux"
api: ["1.0.0"]
website: "https://cavetale.com"
