name: SQL
description: SQL library for Spigot. Replacement for Ebean.
author: StarTux
version: 0.1
website: https://cavetale.com
main: com.winthier.sql.SQLPlugin
depend: []
commands: {}
permissions: {}
